version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: lein deps
      - run: lein do test, uberjar
